package com.example.whynot;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.util.ArrayList;

import org.apache.http.HttpEntity;
import org.apache.http.HttpResponse;
import org.apache.http.StatusLine;
import org.apache.http.client.ClientProtocolException;
import org.apache.http.client.HttpClient;
import org.apache.http.client.methods.HttpPost;
import org.apache.http.entity.StringEntity;
import org.apache.http.impl.client.DefaultHttpClient;

import android.annotation.SuppressLint;
import android.app.Activity;
import android.content.Intent;
import android.os.Build;
import android.os.Bundle;
import android.os.StrictMode;
import android.support.v4.app.NavUtils;
import android.util.Log;
import android.view.Menu;
import android.view.MenuItem;
import android.view.View;
import android.widget.EditText;

public class DisplayGiveActivity extends Activity {
	public static ArrayList<String> CHALLENGES = new ArrayList<String>();

	@SuppressLint("NewApi")
	@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		setContentView(R.layout.activity_display_give);
		// Show the Up button in the action bar.
		setupActionBar();
	}

	/**
	 * Set up the {@link android.app.ActionBar}.
	 */
	private void setupActionBar() {
		if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.HONEYCOMB) {
			getActionBar().setDisplayHomeAsUpEnabled(true);
		}
	}

	@Override
	public boolean onCreateOptionsMenu(Menu menu) {
		// Inflate the menu; this adds items to the action bar if it is present.
		getMenuInflater().inflate(R.menu.display_give, menu);
		return true;
	}

	@Override
	public boolean onOptionsItemSelected(MenuItem item) {
		switch (item.getItemId()) {
		case android.R.id.home:
			// This ID represents the Home or Up button. In the case of this
			// activity, the Up button is shown. Use NavUtils to allow users
			// to navigate up one level in the application structure. For
			// more details, see the Navigation pattern on Android Design:
			//
			// http://developer.android.com/design/patterns/navigation.html#up-vs-back
			//
			NavUtils.navigateUpFromSameTask(this);
			return true;
		}
		return super.onOptionsItemSelected(item);
	}
	
	// submit users challenge to Firebase
	public void go_Submit(View view) {
//		Firebase ref = new Firebase("https://sweltering-fire-3749.firebaseio.com/");
//		Firebase challenges = ref.child("challenges");
//		// Generate a reference to a new location with push()
//		Firebase newPushRef = challenges.push();
//		EditText editText = (EditText) findViewById(R.id.submission);
//    	String message = editText.getText().toString();
//		// Set some data to the generated location
//		newPushRef.setValue(message);
//
//		// Get the name generated by push
//		String pushedName = newPushRef.getName();
//		CHALLENGES.add(pushedName);
//		System.out.println(CHALLENGES);
		
		EditText editText = (EditText) findViewById(R.id.submission);
    	String message = editText.getText().toString();
    	
		  StrictMode.ThreadPolicy policy = new StrictMode.
				  ThreadPolicy.Builder().permitAll().build();
				    StrictMode.setThreadPolicy(policy); 
    	
    	StringBuilder builder = new StringBuilder();
        HttpClient client = new DefaultHttpClient();
        HttpPost httpPost = new HttpPost("http://hbpchallenge.herokuapp.com/challenge");
        try {
        	StringEntity params = new StringEntity("{ 'description' :" + message + "}");
        	System.out.println(params);
        	httpPost.addHeader("content-type", "application/json");
        	httpPost.setEntity(params);
          HttpResponse response = client.execute(httpPost);
          StatusLine statusLine = response.getStatusLine();
          int statusCode = statusLine.getStatusCode();
          if (statusCode == 200) {
            HttpEntity entity = response.getEntity();
            InputStream content = entity.getContent();
            BufferedReader reader = new BufferedReader(new InputStreamReader(content));
            String line;
            while ((line = reader.readLine()) != null) {
              builder.append(line);
            }
          } else {
            Log.e(DisplayExploreActivity.class.toString(), "Failed to download file");
          }
        } catch (ClientProtocolException e) {
          e.printStackTrace();
        } catch (IOException e) {
          e.printStackTrace();
        }
		
		// After submitting go to Confirmation/SubmitAnother Screen
		Intent intent = new Intent(this, DisplayGiveConfirmationActivity.class);
    	startActivity(intent);
		
		
	}

}
